use phf;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ArgType {
  Float,
  Long,
  String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ResType {
  Float,
  Long,
}

mwprocs! {
  Disable(| s),
  Enable(| s),
  MessageBox(s | s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s s),
  Return(),
  StartScript(s),
  StopScript(s),
  // AI
  AIActivate(s | l),
  AITravel(f f f | l),
  AIEscort(s f f f f | l),
  AIEscortCell(s s f f f f | l),
  AIWander(f f f | l l l l l l l l l l),
  AIFollow(s f f f f | l l l l l l l l),
  AIFollowCell(s s f f f f | l),
  SetHello(l),
  SetFight(l),
  SetFlee(l),
  SetAlarm(l),
  ModHello(l),
  ModFight(l),
  ModFlee(l),
  ModAlarm(l),
  ToggleAI(),
  TAI(),
  StartCombat(s),
  StopCombat(| s),
  Face(f f | f), // TODO: extra arg?
  // Animation
  SkipAnim(),
  PlayGroup(s | l),
  LoopGroup(s l | l),
  // Cell
  COC(s),
  CenterOnCell(s),
  COE(l l),
  CenterOnExterior(l l),
  SetWaterLevel(f),
  ModWaterLevel(f),
  // Container
  AddItem(s l),
  RemoveItem(s l),
  Equip(s),
  // Control
  EnablePlayerControls(),
  EnablePlayerFighting(),
  EnablePlayerJumping(),
  EnablePlayerLooking(),
  EnablePlayerMagic(),
  EnablePlayerViewSwitch(),
  EnableVanityMode(),
  DisablePlayerControls(),
  DisablePlayerFighting(),
  DisablePlayerJumping(),
  DisablePlayerLooking(),
  DisablePlayerMagic(),
  DisablePlayerViewSwitch(),
  DisableVanityMode(),
  ToggleCollision(),
  TCL(),
  ClearForceRun(),
  ForceRun(),
  ClearForceJump(),
  ForceJump(),
  ClearForceMoveJump(),
  ForceMoveJump(),
  ClearForceSneak(),
  ForceSneak(),
  // Dialogue
  Journal(s l),
  SetJournalIndex(s l),
  AddTopic(s),
  Choice(| s l s l s l s l s l s l s l s l s l s l s l s l s l s l s l s l s l s l s l s l s l s l s l s l),
  ForceGreeting(),
  Goodbye(),
  SetReputation(l),
  ModReputation(l),
  ModFactionReaction(s s l),
  SetFactionReaction(s s l),
  ClearInfoActor(),
  // Gui
  EnableBirthMenu(),
  EnableClassMenu(),
  EnableNameMenu(),
  EnableRaceMenu(),
  EnableStatReviewMenu(),
  EnableInventoryMenu(),
  EnableMagicMenu(),
  EnableMapMenu(),
  EnableStatsMenu(),
  EnableRest(),
  EnableLevelupMenu(),
  ShowRestMenu(),
  ToggleFogOfWar(),
  TFOW(),
  ToggleFullHelp(),
  TFH(),
  ShowMap(s),
  FillMap(),
  MenuTest(| l),
  ToggleMenus(),
  TM(),
  // Misc
  Activate(),
  Lock(| l),
  Unlock(),
  Cast(s s),
  ExplodeSpell(s),
  ToggleCollisionBoxes(),
  ToggleCollisionGrid(),
  TCB(),
  TCG(),
  TWF(),
  ToggleWireFrame(),
  FadeIn(f),
  FadeOut(f),
  FadeTo(f f),
  ToggleWater(),
  TWA(),
  ToggleWorld(),
  TW(),
  TogglePathGrid(),
  TPG(),
  DontSaveObject(),
  PCForce1stPerson(),
  PCForce3rdPerson(),
  ToggleVanityMode(),
  TVM(),
  WakeUpPC(),
  PlayBink(s l),
  PayFine(),
  PayFineThief(),
  GoToJail(),
  AddSoulGem(s s),
  RemoveSoulGem(s | l),
  Drop(s l),
  DropSoulGem(s),
  SetDelete(l),
  Fall(),
  HurtStandingActor(f),
  HurtCollidingActor(f),
  DisableTeleporting(),
  EnableTeleporting(),
  ShowVars(),
  Show(s),
  SV(),
  TGM(),
  ToggleGodMode(),
  ToggleScripts(),
  DisableLevitation(),
  EnableLevitation(),
  BetaComment(| s),
  BC(| s),
  ORI(| s),
  ShowSceneGraph(| l),
  SSG(| l),
  AddToLevCreature(s s l),
  RemoveFromLevCreature(s s l),
  AddToLevItem(s s l),
  RemoveFromLevItem(s s l),
  TB(),
  ToggleBorders(),
  // Sky
  ToggleSky(),
  TS(),
  TurnMoonWhite(),
  TurnMoonRed(),
  ChangeWeather(s l),
  ModRegion(s | l l l l l l l l l l),
  // Sound
  Say(s s),
  StreamMusic(s),
  PlaySound(s),
  PlaySoundVP(s f f),
  PlaySound3D(s),
  PlaySound3DVP(s f f),
  PlayLoopSound3D(s),
  PlayLoopSound3DVP(s f f),
  StopSound(s),
  // Stats
  SetStrength(l),
  SetIntelligence(l),
  SetWillpower(l),
  SetAgility(l),
  SetSpeed(l),
  SetEndurance(l),
  SetPersonality(l),
  SetLuck(l),
  ModStrength(l),
  ModIntelligence(l),
  ModWillpower(l),
  ModAgility(l),
  ModSpeed(l),
  ModEndurance(l),
  ModPersonality(l),
  ModLuck(l),
  SetHealth(f),
  SetMagicka(f),
  SetFatigue(f),
  ModHealth(f),
  ModMagicka(f),
  ModFatigue(f),
  ModCurrentHealth(f),
  ModCurrentMagicka(f),
  ModCurrentFatigue(f),
  SetBlock(l),
  SetArmorer(l),
  SetMediumArmor(l),
  SetHeavyArmor(l),
  SetBluntWeapon(l),
  SetLongBlade(l),
  SetAxe(l),
  SetSpear(l),
  SetAthletics(l),
  SetEnchant(l),
  SetDestruction(l),
  SetAlteration(l),
  SetIllusion(l),
  SetConjuration(l),
  SetMysticism(l),
  SetRestoration(l),
  SetAlchemy(l),
  SetUnarmored(l),
  SetSecurity(l),
  SetSneak(l),
  SetAcrobatics(l),
  SetLightarmor(l),
  SetShortBlade(l),
  SetMarksman(l),
  SetMercantile(l),
  SetSpeechcraft(l),
  SetHandToHand(l),
  ModBlock(l),
  ModArmorer(l),
  ModMediumArmor(l),
  ModHeavyArmor(l),
  ModBluntWeapon(l),
  ModLongBlade(l),
  ModAxe(l),
  ModSpear(l),
  ModAthletics(l),
  ModEnchant(l),
  ModDestruction(l),
  ModAlteration(l),
  ModIllusion(l),
  ModConjuration(l),
  ModMysticism(l),
  ModRestoration(l),
  ModAlchemy(l),
  ModUnarmored(l),
  ModSecurity(l),
  ModSneak(l),
  ModAcrobatics(l),
  ModLightarmor(l),
  ModShortBlade(l),
  ModMarksman(l),
  ModMercantile(l),
  ModSpeechcraft(l),
  ModHandToHand(l),
  SetResistMagicka(l),
  SetResistFire(l),
  SetResistFrost(l),
  SetResistShock(l),
  SetResistDisease(l),
  SetResistBlight(l),
  SetResistCorprus(l),
  SetResistPoison(l),
  SetResistParalysis(l),
  SetResistNormalWeapons(l),
  SetWaterBreathing(l),
  SetChameleon(l),
  SetWaterWalking(l),
  SetSwimSpeed(l),
  SetSuperJump(l),
  SetFlying(l),
  SetArmorBonus(l),
  SetCastPenalty(l),
  SetSilence(l),
  SetBlindness(l),
  SetParalysis(l),
  SetInvisible(l),
  SetAttackBonus(l),
  SetDefendBonus(l),
  ModResistMagicka(l),
  ModResistFire(l),
  ModResistFrost(l),
  ModResistShock(l),
  ModResistDisease(l),
  ModResistBlight(l),
  ModResistCorprus(l),
  ModResistPoison(l),
  ModResistParalysis(l),
  ModResistNormalWeapons(l),
  ModWaterBreathing(l),
  ModChameleon(l),
  ModWaterWalking(l),
  ModSwimSpeed(l),
  ModSuperJump(l),
  ModFlying(l),
  ModArmorBonus(l),
  ModCastPenalty(l),
  ModSilence(l),
  ModBlindness(l),
  ModParalysis(l),
  ModInvisible(l),
  ModAttackBonus(l),
  ModDefendBonus(l),
  SetPCCrimeLevel(f),
  ModPCCrimeLevel(f),
  AddSpell(s),
  RemoveSpell(s),
  RemoveSpellEffects(s),
  RemoveEffects(l),
  Resurrect(),
  PCRaiseRank(| s),
  PCLowerRank(| s),
  PCJoinFaction(| s),
  ModDisposition(l),
  SetDisposition(l),
  SetLevel(l),
  SetPCFacRep(l | s),
  ModPCFacRep(l | s),
  PCExpell(| s),
  PCClearExpelled(| s),
  RaiseRank(),
  LowerRank(),
  BecomeWerewolf(),
  UndoWerewolf(),
  SetWerewolfAcrobatics(),
  // Transformation
  SetScale(f),
  SetAngle(s f),
  SetPos(s f),
  Position(f f f f),
  PositionCell(f f f f s),
  PlaceItemCell(s s f f f f),
  PlaceItem(s f f f f),
  PlaceAtPC(s l f l),
  PlaceAtMe(s l f l),
  ModScale(f),
  Rotate(s f),
  RotateWorld(s f),
  SetAtStart(),
  Move(s f),
  MoveWorld(s f),
  ResetActors(),
  FixMe(),
  RA()
}

mwfuncs! {
  GetDisabled(| s): l,
  GetDistance(s): f,
  GetSecondsPassed(): f,
  MenuMode(): l,
  Random(l): l,
  ScriptRunning(s): l,
  // AI
  GetAIPackageDone(): l,
  GetCurrentAIPackage(): l,
  GetDetected(s): l,
  GetHello(): l,
  GetFight(): l,
  GetFlee(): l,
  GetAlarm(): l,
  GetLineOfSight(s): l,
  GetLOS(s): l,
  GetTarget(s): l,
  // Cell
  CellChanged(): l,
  GetInterior(): l,
  GetPCCell(s): l,
  GetWaterLevel(): f,
  // Container
  GetItemCount(s): l,
  GetArmorType(l): l,
  HasItemEquipped(s): l,
  HasSoulgem(s): l,
  GetWeaponType(): l,
  // Control
  GetPlayerControls(): l,
  GetPlayerFighting(): l,
  GetPlayerJumping(): l,
  GetPlayerLooking(): l,
  GetPlayerMagic(): l,
  GetPlayerViewSwitch(): l,
  GetVanityMode(): l,
  GetPCRunning(): l,
  GetPCSneaking(): l,
  GetForceRun(): l,
  GetForceJump(): l,
  GetForceMoveJump(): l,
  GetForceSneak(): l,
  // Dialogue
  GetJournalIndex(s): l,
  GetReputation(): l,
  SameFaction(): l,
  GetFactionReaction(s s | l): l,
  // Gui
  GetButtonPressed(): l,
  // Misc
  XBox(): l,
  OnActivate(): l,
  PCGet3rdPerson(): l,
  GetPCSleep(): l,
  GetPCJumping(): l,
  GetLocked(): l,
  GetEffect(s): l,
  GetAttacked(): l,
  GetWeaponDrawn(): l,
  GetSpellReadied(): l,
  GetSpellEffects(s): l,
  GetCurrentTime(): f,
  GetSquareRoot(f): f,
  GetStandingPC(): l,
  GetStandingActor(): l,
  GetCollidingPC(): l,
  GetCollidingActor(): l,
  GetWindSpeed(): f,
  HitOnMe(s): l,
  HitAttemptOnMe(s): l,
  GetPCInJail(): l,
  GetPCTraveling(): l,
  // Sky
  GetMasserPhase(): l,
  GetSecundaPhase(): l,
  GetCurrentWeather(): l,
  // Sound
  SayDone(): l,
  GetSoundPlaying(s): l,
  // Stats
  GetStrength(): l,
  GetIntelligence(): l,
  GetWillpower(): l,
  GetAgility(): l,
  GetSpeed(): l,
  GetEndurance(): l,
  GetPersonality(): l,
  GetLuck(): l,
  GetHealth(): f,
  GetMagicka(): f,
  GetFatigue(): f,
  GetHealthGetRatio(): f,
  GetMagickaGetRatio(): f,
  GetFatigueGetRatio(): f,
  GetBlock(): l,
  GetArmorer(): l,
  GetMediumArmor(): l,
  GetHeavyArmor(): l,
  GetBluntWeapon(): l,
  GetLongBlade(): l,
  GetAxe(): l,
  GetSpear(): l,
  GetAthletics(): l,
  GetEnchant(): l,
  GetDestruction(): l,
  GetAlteration(): l,
  GetIllusion(): l,
  GetConjuration(): l,
  GetMysticism(): l,
  GetRestoration(): l,
  GetAlchemy(): l,
  GetUnarmored(): l,
  GetSecurity(): l,
  GetSneak(): l,
  GetAcrobatics(): l,
  GetLightarmor(): l,
  GetShortBlade(): l,
  GetMarksman(): l,
  GetMercantile(): l,
  GetSpeechcraft(): l,
  GetHandToHand(): l,
  GetResistMagicka(): l,
  GetResistFire(): l,
  GetResistFrost(): l,
  GetResistShock(): l,
  GetResistDisease(): l,
  GetResistBlight(): l,
  GetResistCorprus(): l,
  GetResistPoison(): l,
  GetResistParalysis(): l,
  GetResistNormalWeapons(): l,
  GetWaterBreathing(): l,
  GetChameleon(): l,
  GetWaterWalking(): l,
  GetSwimSpeed(): l,
  GetSuperJump(): l,
  GetFlying(): l,
  GetArmorBonus(): l,
  GetCastPenalty(): l,
  GetSilence(): l,
  GetBlindness(): l,
  GetParalysis(): l,
  GetInvisible(): l,
  GetAttackBonus(): l,
  GetDefendBonus(): l,
  GetPCCrimeLevel(): f,
  GetSpell(s): l,
  GetDisposition(): l,
  GetPCRank(| s): l,
  GetLevel(): l,
  GetStat(s): l,
  GetDeadCount(s): l,
  GetPCFacRep(| s): l,
  GetCommonDisease(): l,
  GetBlightDisease(): l,
  GetRace(s): l,
  GetWerewolfKills(): l,
  PCExpelled(| s): l,
  OnDeath(): l,
  OnMurder(): l,
  OnKnockout(): l,
  IsWerewolf(): l,
  // Transformation
  GetScale(): f,
  GetAngle(s): f,
  GetPos(s): f,
  GetStartingPos(s): f,
  GetStartingAngle(s): f
}

include!(concat!(env!("OUT_DIR"), "/codegen.rs"));
